### ISSUE TITLE
Forward wheels rotation when drift 

### ISSUE THREAD

**Issue by tanakasama** [RandomationGames/Randomation-Vehicle-Physics#19]
When car drifting, in the real world, the forward wheels rotation will be rotate follow car moving direction, but in RVP, forward wheels rotation not like that. Could improve this thing which look like real drift behaviour ?

**Comment by RandomationGames** [comment]
The drifting is not very realistic because of the VehicleAssist script. It helps to better control vehicles by "cheating" and applying forces directly to the rigidbody instead of allowing the wheels to naturally guide it. You can disable the script to get more realistic behavior, but it will be more difficult to control.

**Comment by tanakasama** [comment]
But, we can check when car drifting, we will rotate front wheels like real drifting ?

**Comment by RandomationGames** [comment]
You can do that if you want, since it's open source. I don't think it belongs in the public repository though.
